import Nio
import numpy as np
import numpy.testing as nt
import os
import unittest as ut

file_to_test = '../ncarg/data/grib2/wafsgfs_L_t06z_intdsk60.grib2'

class Test(ut.TestCase):
    def setUp(self):
        self.f = Nio.open_file(os.path.realpath(os.path.join(os.path.dirname(__file__), file_to_test)))

    def test_grib2_variables(self):
        nt.assert_equal(set(self.f.variables.keys()), set(file_variables))

    def test_grib2_attributes(self):
        nt.assert_equal(self.f.attributes, file_attributes)

    def test_grib2_dimensions(self):
        nt.assert_equal(self.f.dimensions, file_dimensions)

    def test_grib2_var_shapes(self):
        for var in self.f.variables.keys():
            v = self.f.variables[var]
            nt.assert_equal(v.shape, var_shapes[var])

    def test_grib2_var_attributes(self):
        for var in self.f.variables.keys():
            v = self.f.variables[var]
            nt.assert_equal(v.attributes, var_attributes[var])

    def test_grib2_var_dimensions(self):
        for var in self.f.variables.keys():
            v = self.f.variables[var]
            nt.assert_equal(v.dimensions, var_dimensions[var])

    def test_grib2_var_coordinates(self):
        for var in self.f.variables.keys():
            v = self.f.variables[var]
            nt.assert_equal(get_coord_dims(v), var_coordinates[var])


file_attributes = {}
file_dimensions = {'lat_0': 73, 'lon_0': 73, 'lv_ISBL0': 12, 'lv_ISBL1': 11, 'lv_ISBL2': 10}
file_variables = ['TMP_P0_L6_GLL0', 'TMP_P0_L7_GLL0', 'TMP_P0_L100_GLL0', 'TMP_P0_L103_GLL0', 'TMP_P0_2L108_GLL0', 'RH_P0_L100_GLL0', 'RH_P0_L103_GLL0', 'RH_P0_2L108_GLL0', 'UGRD_P0_L6_GLL0', 'UGRD_P0_L7_GLL0', 'UGRD_P0_L100_GLL0', 'UGRD_P0_L103_GLL0', 'UGRD_P0_2L108_GLL0', 'VGRD_P0_L6_GLL0', 'VGRD_P0_L7_GLL0', 'VGRD_P0_L100_GLL0', 'VGRD_P0_L103_GLL0', 'VGRD_P0_2L108_GLL0', 'VVEL_P0_L100_GLL0', 'ABSV_P0_L100_GLL0', 'PRES_P0_L1_GLL0', 'PRES_P0_L6_GLL0', 'PRES_P0_L7_GLL0', 'PRMSL_P0_L101_GLL0', 'HGT_P0_L6_GLL0', 'HGT_P0_L7_GLL0', 'HGT_P0_L100_GLL0', 'APCP_P8_L1_GLL0_acc6h', 'ACPCP_P8_L1_GLL0_acc6h', 'lv_ISBL2', 'lv_ISBL1', 'lv_ISBL0', 'lat_0', 'lon_0']

var_attributes = {'TMP_P0_L6_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Temperature', 'units': 'K', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Temperature', 'parameter_template_discipline_category_number': np.array([0, 0, 0, 0], dtype=np.int32), 'level_type': 'Maximum wind level', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'TMP_P0_L7_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Temperature', 'units': 'K', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Temperature', 'parameter_template_discipline_category_number': np.array([0, 0, 0, 0], dtype=np.int32), 'level_type': 'Tropopause', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'TMP_P0_L100_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Temperature', 'units': 'K', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Temperature', 'parameter_template_discipline_category_number': np.array([0, 0, 0, 0], dtype=np.int32), 'level_type': 'Isobaric surface (Pa)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'TMP_P0_L103_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Temperature', 'units': 'K', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Temperature', 'parameter_template_discipline_category_number': np.array([0, 0, 0, 0], dtype=np.int32), 'level_type': 'Specified height level above ground (m)', 'level': np.array([2.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'TMP_P0_2L108_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Temperature', 'units': 'K', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Temperature', 'parameter_template_discipline_category_number': np.array([0, 0, 0, 0], dtype=np.int32), 'level_type': 'Level at specified pressure difference from ground to level (Pa)', 'level': np.array([3000.,    0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'RH_P0_L100_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Relative humidity', 'units': '%', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Moisture', 'parameter_template_discipline_category_number': np.array([0, 0, 1, 1], dtype=np.int32), 'level_type': 'Isobaric surface (Pa)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'RH_P0_L103_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Relative humidity', 'units': '%', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Moisture', 'parameter_template_discipline_category_number': np.array([0, 0, 1, 1], dtype=np.int32), 'level_type': 'Specified height level above ground (m)', 'level': np.array([2.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'RH_P0_2L108_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Relative humidity', 'units': '%', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Moisture', 'parameter_template_discipline_category_number': np.array([0, 0, 1, 1], dtype=np.int32), 'level_type': 'Level at specified pressure difference from ground to level (Pa)', 'level': np.array([3000.,    0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'UGRD_P0_L6_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'U-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 2], dtype=np.int32), 'level_type': 'Maximum wind level', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'UGRD_P0_L7_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'U-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 2], dtype=np.int32), 'level_type': 'Tropopause', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'UGRD_P0_L100_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'U-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 2], dtype=np.int32), 'level_type': 'Isobaric surface (Pa)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'UGRD_P0_L103_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'U-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 2], dtype=np.int32), 'level_type': 'Specified height level above ground (m)', 'level': np.array([10.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'UGRD_P0_2L108_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'U-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 2], dtype=np.int32), 'level_type': 'Level at specified pressure difference from ground to level (Pa)', 'level': np.array([3000.,    0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'VGRD_P0_L6_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'V-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 3], dtype=np.int32), 'level_type': 'Maximum wind level', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'VGRD_P0_L7_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'V-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 3], dtype=np.int32), 'level_type': 'Tropopause', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'VGRD_P0_L100_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'V-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 3], dtype=np.int32), 'level_type': 'Isobaric surface (Pa)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'VGRD_P0_L103_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'V-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 3], dtype=np.int32), 'level_type': 'Specified height level above ground (m)', 'level': np.array([10.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'VGRD_P0_2L108_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'V-component of wind', 'units': 'm s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 3], dtype=np.int32), 'level_type': 'Level at specified pressure difference from ground to level (Pa)', 'level': np.array([3000.,    0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'VVEL_P0_L100_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Vertical velocity (pressure)', 'units': 'Pa s-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([0, 0, 2, 8], dtype=np.int32), 'level_type': 'Isobaric surface (Pa)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'ABSV_P0_L100_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Absolute vorticity', 'units': 's-1', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Momentum', 'parameter_template_discipline_category_number': np.array([ 0,  0,  2, 10], dtype=np.int32), 'level_type': 'Isobaric surface (Pa)', 'level': np.array([50000.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'PRES_P0_L1_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Pressure', 'units': 'Pa', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Mass', 'parameter_template_discipline_category_number': np.array([0, 0, 3, 0], dtype=np.int32), 'level_type': 'Ground or water surface', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'PRES_P0_L6_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Pressure', 'units': 'Pa', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Mass', 'parameter_template_discipline_category_number': np.array([0, 0, 3, 0], dtype=np.int32), 'level_type': 'Maximum wind level', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'PRES_P0_L7_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Pressure', 'units': 'Pa', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Mass', 'parameter_template_discipline_category_number': np.array([0, 0, 3, 0], dtype=np.int32), 'level_type': 'Tropopause', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'PRMSL_P0_L101_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Pressure reduced to MSL', 'units': 'Pa', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Mass', 'parameter_template_discipline_category_number': np.array([0, 0, 3, 1], dtype=np.int32), 'level_type': 'Mean sea level (Pa)', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'HGT_P0_L6_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Geopotential height', 'units': 'gpm', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Mass', 'parameter_template_discipline_category_number': np.array([0, 0, 3, 5], dtype=np.int32), 'level_type': 'Maximum wind level', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'HGT_P0_L7_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Geopotential height', 'units': 'gpm', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Mass', 'parameter_template_discipline_category_number': np.array([0, 0, 3, 5], dtype=np.int32), 'level_type': 'Tropopause', 'level': np.array([0.], dtype=np.float32), 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'HGT_P0_L100_GLL0': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Geopotential height', 'units': 'gpm', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Mass', 'parameter_template_discipline_category_number': np.array([0, 0, 3, 5], dtype=np.int32), 'level_type': 'Isobaric surface (Pa)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'APCP_P8_L1_GLL0_acc6h': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Total precipitation', 'units': 'kg m-2', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Moisture', 'parameter_template_discipline_category_number': np.array([8, 0, 1, 8], dtype=np.int32), 'level_type': 'Ground or water surface', 'level': np.array([0.], dtype=np.float32), 'type_of_statistical_processing': 'Accumulation', 'statistical_process_duration': '6 hours (ending at forecast time)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'ACPCP_P8_L1_GLL0_acc6h': {'center': 'US National Weather Service - NCEP (WMC)', 'production_status': 'Operational products', 'long_name': 'Convective precipitation', 'units': 'kg m-2', '_FillValue': np.array([1.e+20], dtype=np.float32), 'grid_type': 'Latitude/longitude (quasi-regular grid expanded by cubic interpolation)', 'parameter_discipline_and_category': 'Meteorological products, Moisture', 'parameter_template_discipline_category_number': np.array([ 8,  0,  1, 10], dtype=np.int32), 'level_type': 'Ground or water surface', 'level': np.array([0.], dtype=np.float32), 'type_of_statistical_processing': 'Accumulation', 'statistical_process_duration': '6 hours (ending at forecast time)', 'forecast_time': np.array([60], dtype=np.int32), 'forecast_time_units': 'hours', 'initial_time': '01/10/2007 (06:00)'},
                  'lv_ISBL2': {'long_name': 'Isobaric surface', 'units': 'Pa'},
                  'lv_ISBL1': {'long_name': 'Isobaric surface', 'units': 'Pa'},
                  'lv_ISBL0': {'long_name': 'Isobaric surface', 'units': 'Pa'},
                  'lat_0': {'long_name': 'latitude', 'grid_type': 'Latitude/longitude Grid (Quasi-Regular)', 'units': 'degrees_north', 'Dj': np.array([1.25], dtype=np.float32), 'Di': np.array([1.25], dtype=np.float32), 'Lo2': np.array([330.], dtype=np.float32), 'La2': np.array([90.], dtype=np.float32), 'Lo1': np.array([240.], dtype=np.float32), 'La1': np.array([0.], dtype=np.float32)},
                  'lon_0': {'long_name': 'longitude', 'grid_type': 'Latitude/longitude Grid (Quasi-Regular)', 'units': 'degrees_east', 'Dj': np.array([1.25], dtype=np.float32), 'Di': np.array([1.25], dtype=np.float32), 'Lo2': np.array([330.], dtype=np.float32), 'La2': np.array([90.], dtype=np.float32), 'Lo1': np.array([240.], dtype=np.float32), 'La1': np.array([0.], dtype=np.float32)}}
var_coordinates = {'TMP_P0_L6_GLL0': ['lat_0', 'lon_0'], 'TMP_P0_L7_GLL0': ['lat_0', 'lon_0'], 'TMP_P0_L100_GLL0': ['lv_ISBL0', 'lat_0', 'lon_0'], 'TMP_P0_L103_GLL0': ['lat_0', 'lon_0'], 'TMP_P0_2L108_GLL0': ['lat_0', 'lon_0'], 'RH_P0_L100_GLL0': ['lv_ISBL1', 'lat_0', 'lon_0'], 'RH_P0_L103_GLL0': ['lat_0', 'lon_0'], 'RH_P0_2L108_GLL0': ['lat_0', 'lon_0'], 'UGRD_P0_L6_GLL0': ['lat_0', 'lon_0'], 'UGRD_P0_L7_GLL0': ['lat_0', 'lon_0'], 'UGRD_P0_L100_GLL0': ['lv_ISBL0', 'lat_0', 'lon_0'], 'UGRD_P0_L103_GLL0': ['lat_0', 'lon_0'], 'UGRD_P0_2L108_GLL0': ['lat_0', 'lon_0'], 'VGRD_P0_L6_GLL0': ['lat_0', 'lon_0'], 'VGRD_P0_L7_GLL0': ['lat_0', 'lon_0'], 'VGRD_P0_L100_GLL0': ['lv_ISBL0', 'lat_0', 'lon_0'], 'VGRD_P0_L103_GLL0': ['lat_0', 'lon_0'], 'VGRD_P0_2L108_GLL0': ['lat_0', 'lon_0'], 'VVEL_P0_L100_GLL0': ['lv_ISBL2', 'lat_0', 'lon_0'], 'ABSV_P0_L100_GLL0': ['lat_0', 'lon_0'], 'PRES_P0_L1_GLL0': ['lat_0', 'lon_0'], 'PRES_P0_L6_GLL0': ['lat_0', 'lon_0'], 'PRES_P0_L7_GLL0': ['lat_0', 'lon_0'], 'PRMSL_P0_L101_GLL0': ['lat_0', 'lon_0'], 'HGT_P0_L6_GLL0': ['lat_0', 'lon_0'], 'HGT_P0_L7_GLL0': ['lat_0', 'lon_0'], 'HGT_P0_L100_GLL0': ['lv_ISBL0', 'lat_0', 'lon_0'], 'APCP_P8_L1_GLL0_acc6h': ['lat_0', 'lon_0'], 'ACPCP_P8_L1_GLL0_acc6h': ['lat_0', 'lon_0'], 'lv_ISBL2': ['lv_ISBL2'], 'lv_ISBL1': ['lv_ISBL1'], 'lv_ISBL0': ['lv_ISBL0'], 'lat_0': ['lat_0'], 'lon_0': ['lon_0']}
var_dimensions = {'TMP_P0_L6_GLL0': ('lat_0', 'lon_0'), 'TMP_P0_L7_GLL0': ('lat_0', 'lon_0'), 'TMP_P0_L100_GLL0': ('lv_ISBL0', 'lat_0', 'lon_0'), 'TMP_P0_L103_GLL0': ('lat_0', 'lon_0'), 'TMP_P0_2L108_GLL0': ('lat_0', 'lon_0'), 'RH_P0_L100_GLL0': ('lv_ISBL1', 'lat_0', 'lon_0'), 'RH_P0_L103_GLL0': ('lat_0', 'lon_0'), 'RH_P0_2L108_GLL0': ('lat_0', 'lon_0'), 'UGRD_P0_L6_GLL0': ('lat_0', 'lon_0'), 'UGRD_P0_L7_GLL0': ('lat_0', 'lon_0'), 'UGRD_P0_L100_GLL0': ('lv_ISBL0', 'lat_0', 'lon_0'), 'UGRD_P0_L103_GLL0': ('lat_0', 'lon_0'), 'UGRD_P0_2L108_GLL0': ('lat_0', 'lon_0'), 'VGRD_P0_L6_GLL0': ('lat_0', 'lon_0'), 'VGRD_P0_L7_GLL0': ('lat_0', 'lon_0'), 'VGRD_P0_L100_GLL0': ('lv_ISBL0', 'lat_0', 'lon_0'), 'VGRD_P0_L103_GLL0': ('lat_0', 'lon_0'), 'VGRD_P0_2L108_GLL0': ('lat_0', 'lon_0'), 'VVEL_P0_L100_GLL0': ('lv_ISBL2', 'lat_0', 'lon_0'), 'ABSV_P0_L100_GLL0': ('lat_0', 'lon_0'), 'PRES_P0_L1_GLL0': ('lat_0', 'lon_0'), 'PRES_P0_L6_GLL0': ('lat_0', 'lon_0'), 'PRES_P0_L7_GLL0': ('lat_0', 'lon_0'), 'PRMSL_P0_L101_GLL0': ('lat_0', 'lon_0'), 'HGT_P0_L6_GLL0': ('lat_0', 'lon_0'), 'HGT_P0_L7_GLL0': ('lat_0', 'lon_0'), 'HGT_P0_L100_GLL0': ('lv_ISBL0', 'lat_0', 'lon_0'), 'APCP_P8_L1_GLL0_acc6h': ('lat_0', 'lon_0'), 'ACPCP_P8_L1_GLL0_acc6h': ('lat_0', 'lon_0'), 'lv_ISBL2': ('lv_ISBL2',), 'lv_ISBL1': ('lv_ISBL1',), 'lv_ISBL0': ('lv_ISBL0',), 'lat_0': ('lat_0',), 'lon_0': ('lon_0',)}
var_shapes = {'TMP_P0_L6_GLL0': (73, 73), 'TMP_P0_L7_GLL0': (73, 73), 'TMP_P0_L100_GLL0': (12, 73, 73), 'TMP_P0_L103_GLL0': (73, 73), 'TMP_P0_2L108_GLL0': (73, 73), 'RH_P0_L100_GLL0': (11, 73, 73), 'RH_P0_L103_GLL0': (73, 73), 'RH_P0_2L108_GLL0': (73, 73), 'UGRD_P0_L6_GLL0': (73, 73), 'UGRD_P0_L7_GLL0': (73, 73), 'UGRD_P0_L100_GLL0': (12, 73, 73), 'UGRD_P0_L103_GLL0': (73, 73), 'UGRD_P0_2L108_GLL0': (73, 73), 'VGRD_P0_L6_GLL0': (73, 73), 'VGRD_P0_L7_GLL0': (73, 73), 'VGRD_P0_L100_GLL0': (12, 73, 73), 'VGRD_P0_L103_GLL0': (73, 73), 'VGRD_P0_2L108_GLL0': (73, 73), 'VVEL_P0_L100_GLL0': (10, 73, 73), 'ABSV_P0_L100_GLL0': (73, 73), 'PRES_P0_L1_GLL0': (73, 73), 'PRES_P0_L6_GLL0': (73, 73), 'PRES_P0_L7_GLL0': (73, 73), 'PRMSL_P0_L101_GLL0': (73, 73), 'HGT_P0_L6_GLL0': (73, 73), 'HGT_P0_L7_GLL0': (73, 73), 'HGT_P0_L100_GLL0': (12, 73, 73), 'APCP_P8_L1_GLL0_acc6h': (73, 73), 'ACPCP_P8_L1_GLL0_acc6h': (73, 73), 'lv_ISBL2': (10,), 'lv_ISBL1': (11,), 'lv_ISBL0': (12,), 'lat_0': (73,), 'lon_0': (73,)}

def get_coord_dims(var):
    return [dim for dim in var.dimensions if dim in var.file.variables.keys()]

if __name__ == '__main__':
    ut.main()
